DROP DATABASE IF EXISTS ALAS_DE_CRISTAL;
CREATE DATABASE ALAS_DE_CRISTAL;
USE ALAS_DE_CRISTAL;


CREATE TABLE EMPLEADO(
    ID_EMPLEADO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USUARIO VARCHAR(45) NOT NULL,
    CONTRASEÑA VARCHAR(45) NOT NULL,
    ADMININISTRADOR INT
);

CREATE TABLE REGISTRO(
    ID_REGISTRO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FECHA DATE NOT NULL,
    FECHA_ENTRADA TIMESTAMP NOT NULL,
    FECHA_SALIDA TIMESTAMP NULL,
    TOTAL_HORAS INT,
    ID_EMPLEADO INT,
    CONSTRAINT FK_EMPLEADO_REGISTRO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);


CREATE TABLE PRODUCTOS(
    ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(45) NOT NULL,
    STOCK INT NOT NULL,
    DESCRIPCION VARCHAR(10000) NOT NULL,
    PRECIO INT NOT NULL,
    ID_EMPLEADO INT NULL,
    CONSTRAINT FK_EMPLEADO_PRODUCTO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);


CREATE TABLE PRODUCTO_IMAGENES (
    ID_IMAGEN INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUCTO INT NOT NULL,
    CONTENIDO_IMAGEN LONGBLOB NOT NULL,
    CONSTRAINT FK_PRODUCTO_IMAGEN FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO) ON DELETE CASCADE
);

CREATE TABLE CLIENTE (
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
    USUARIO VARCHAR(20) NOT NULL,
    CONTRASEÑA VARCHAR(20) NOT NULL,
    CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE)
);


CREATE TABLE PEDIDO (
    ID_PEDIDO INT NOT NULL AUTO_INCREMENT,
    ENTREGA DATE NULL,
    TELEFONO INT NOT NULL,
    ESTADO VARCHAR(20) NULL,
    ID_CLIENTE INT NULL,
    TOTALPRECIO INT NULL,
    CONSTRAINT PK_ID_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE PEDIDO_PRODUCTO(
    ID_PEDIDO_PRODUCTO INT NOT NULL AUTO_INCREMENT,
    ID_PEDIDO INT NULL,
    ID_PRODUCTO INT NULL,
    CANTIDAD INT NULL,
    CONSTRAINT PK_ID_PEDIDO_PRODUCTO PRIMARY KEY (ID_PEDIDO_PRODUCTO),
    CONSTRAINT FK_ID_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK_ID_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

INSERT INTO EMPLEADO (USUARIO, CONTRASEÑA, ADMININISTRADOR) VALUES ('Admin', 'Pruebas', 1);